
export const partnersPage = {
  id: 'partners', label: 'Partners', crumb: null, path: '/partners', eyebrow: 'ByteFX partnership',
  title: 'Your network.', accent: 'More possibility.',
  description: 'Introduce traders to ByteFX Capital Ltd. and earn up to 40% of the trading fees they generate — with transparent reporting, fast payouts and a relationship manager to help you scale.',
  art: '/assets/generated/refer-partners-grow.webp', lightArt: '/assets/generated/blue/refer-partners-grow-supplied.png',
  alt: 'Two glass profile cards connected by a Partners Grow ring',
  primary: { label: 'Become a partner', href: '#become-ib' }, secondary: { label: 'Explore the benefits', href: '#benefits' },
  stats: [['Up to 40%', 'Revenue share on client trading fees'], ['Instant', 'Commission payouts'], ['1 dashboard', 'Transparent reporting'], ['Dedicated', 'Relationship manager']],
};

export const partnerBenefits = [
  { icon: 'chart', title: 'Instant payouts & transparent reporting', body: 'Access a dedicated dashboard and receive your commissions quickly.' },
  { icon: 'megaphone', title: 'Marketing support', body: 'Professionally designed materials and personalised assistance for your campaigns.' },
  { icon: 'users', title: 'Relationship manager', body: 'Dedicated support for our partners (IBs) to help you scale your business.' },
];

export const partnerSteps = [
  ['Apply', 'Send the enquiry form below. The partnerships team reviews your audience and goals.'],
  ['Get set up', 'Your relationship manager gives you your referral details and partner dashboard.'],
  ['Refer traders', 'Clients open and fund their ByteFX accounts through your referral.'],
  ['Earn', 'Receive up to 40% of your referred clients’ trading fees, with every payout reported.'],
];

export const clientOffer = [
  ['150+', 'instruments across six markets'],
  ['$20', 'minimum deposit on Standard'],
  ['1:2000*', 'maximum leverage'],
  ['~20 ms', 'average execution'],
  ['Instant', 'crypto and USDT withdrawals'],
  ['24/6', 'live chat and email support'],
];

export const partnersFaqs = [
  ['Who can become a ByteFX partner?', 'Partners typically include trading educators, community owners and introducing brokers (IBs). Tell us about your audience in the enquiry form and the team will confirm the fit.'],
  ['How much can I earn?', 'Up to 40% commission on the trading fees generated by the clients you refer. Your rate is confirmed in your partner agreement.'],
  ['How are commissions paid and tracked?', 'Commissions are paid out quickly, and a dedicated partner dashboard shows your referred clients and earnings.'],
  ['What support do partners get?', 'Professionally designed marketing materials, personalised assistance and a dedicated relationship manager.'],
  ['What do my referred clients get?', 'Access to 150+ instruments on MetaTrader 5, accounts from $20, leverage up to 1:2000*, instant crypto withdrawals and 24/6 support.'],
  ['Are there countries where ByteFX is not available?', 'Services are not offered to residents of the UAE, India, USA, China, Iran, North Korea and other sanctioned regions.'],
];
